### ISSUE TITLE
3-deploy-rancher-on-k3s error

### ISSUE THREAD

**Issue by goffinf** [arashkaffamanesh/multipass-rke-rancher#1]
The script: 3-deploy-rancher-on-k3s.sh uses helm to install rancher as follows ...

`helm install --name rancher rancher-latest/rancher ...`

I believe that this should be (note: rancher-stable):

`helm install --name rancher rancher-stable/rancher ...`

**Comment by arashkaffamanesh** [comment]
Thanks for the hint, the latest and greatest works as well on my env.
Did you had problems with the latest?

**Comment by arashkaffamanesh** [comment]
Now using the rancher stable release.

**Comment by goffinf** [comment]
Hey Arash, I did have a problem using latest but most likely because I already had other versions of the helm chart repo installed (see note below from the Rancher docs). Switching to stable fixed that, and is probably a better choice tbh.

The bigger problem is that the scripts don’t really work as/is on Windows for a couple of reasons. The main one is that when running multipass exec that expect and use output, that output is not produced. This is a known issue which the multipass guys have an open issue for. That is exacerbated because multipass cannot be installed within Windows Subsystem for Linux (WSL) because snap isn’t supported since there is no systemd .. so you are left with either the Windows command prompt (which means Linux paths in the scripts are not found) or git bash where paths are ok but multipass output is not available either for variable assignment or to output files. I have worked thru the example scripts, running the commands where they work and produced a successful deployment but automation is compromised (which is what I need before promoting the approach for my team).

That aside, great work with the resources and supporting instructions, very good, and produces a better environment than running k3s for multi-node on Windows (I use k3d at present).

Going to add a metallb external load balancer next to provide a better ingress experience that more closely mirrors my work implementation environment (AWS R53 -> ALB -> Ingress Controller -> Ingress).

Will close this issue. Might raise a separate one for the scripting issues on Windows.

Note:
The introduction of the rancher-latest and rancher-stable Helm Chart repositories was introduced after Rancher v2.1.0, so the rancher-stable repository contains some Rancher versions that were never marked as rancher/rancher:stable. The versions of Rancher that were tagged as rancher/rancher:stable prior to v2.1.0 are v2.0.4, v2.0.6, v2.0.8. Post v2.1.0, all charts in the rancher-stable repository will correspond with any Rancher version tagged as stable.s 

Regards

Fraser.

**Comment by arashkaffamanesh** [comment]
Hey Fraser,

Thanks so much for the great clarification and investigations.
Yes, windows has issues with multipass and the full-automation will be a pain.

But I think this kubeadm-multipass which I implemented today should work on Windows:

https://github.com/arashkaffamanesh/kubeadm-multipass

Thanks again,
Cheers,
Arash
