### ISSUE TITLE
error with SSH key transfer

### ISSUE THREAD

**Issue by penquinspecz** [arashkaffamanesh/multipass-rke-rancher#5]
in ./1-deploy-multipass-vms.sh, I'm having trouble with the following commands:

```
for NODE in ${NODES}; do
multipass transfer hosts ${NODE}:
multipass exec ${NODE} -- bash -c 'sudo chown ubuntu:ubuntu /etc/hosts'
multipass exec ${NODE} -- bash -c 'sudo cat /home/ubuntu/hosts >> /etc/hosts'
multipass transfer ~/.ssh/id_rsa.pub ${NODE}:
multipass exec ${NODE} -- bash -c 'sudo cat /home/ubuntu/id_rsa.pub >> .ssh/authorized_keys'
done
```
(specifically last 3 lines)

I keep receiving the following error: 
```
Source path "/Users/USERNAME/.ssh/id_rsa.pub" does not exist
cat: /home/ubuntu/id_rsa.pub: No such file or directory
```

I did see you had linked a GH issue around transfer command, but to my knowledge, everything is correct? I've tried adjusting the yaml endlessly with no luck. Obviously, the rest of the install errors (specifically establishing SSH tunnels) and fails without this step working. Any help is appreciated!

**Comment by arashkaffamanesh** [comment]
does `~/.ssh/id_rsa.pub` exist on your machine?
Does your user have sudo right?
Which Multipass version are you using?
Are you trying this on linux or mac?

I tested the installation just now with multipass 1.8.0+mac on mac and it still works fine.

**Comment by penguinspecz** [comment]
thanks so much for the help! for some reason by `id_rsa.pub` had become corrupted, simple regeneration fixed it up. Still having some deployment troubles but those are all on my side. This is a brilliant project - thanks so much!
